agent_defaults:
  actuation_noise_x: 0.1
  actuation_noise_y: 0.1
  actuation_noise_theta: 0.1
  observation_noise_x: 1
  observation_noise_y: 1
  observation_noise_theta: 1
  behavior_type: ParametricConstants
  behavior_config:
    - time: 0
      x: 1
      y: 0
      theta: 0
    - time: 500
      x: -1
      y: 0
      theta: 0
    - time: 1000
      x: 1
      y: 0
      theta: 0
    - time: 1500
      x: -1
      y: 0
      theta: 0
    - time: 2000
      x: -1
      y: 0
      theta: 0
agents:
  - id: 1
    x0: 25
    y0: 50
    theta0: 0
  - id: 2
    x0: 75
    y0: 50
    theta0: 0
  - id: 3
    x0: 125
    y0: 50
    theta0: 0
world:
  initial_procedure: pause
  steps_per_frame: 5
  frames_per_second: 12
  limit: 2000
  size:
    - 650
    - 200
visuals:
  scale: 0.5
  steps_per_frame: 10
  frames_per_second: 12
